### ISSUE TITLE
Unsafe for allocation failure

### ISSUE THREAD

**Issue by tlsa** [Tehreer/SheenBidi#13]
At the moment the library calls malloc and uses the result without checking for NULL throughout.

For my use case this makes it unusable. Would it be possible to add allocation failure handling?

**Comment by mta452** [comment]
Can you please shed light on some details of your use case? Is it due to lower memory constraints? Maybe a code snippet?

It can be checked easily on object creation as there are very few malloc calls. But there are some classes, like the `BracketQueue` and the `RunQueue` which create lists on-demand basis. So there would be a need to implement some kind of fail safe mechanism in these cases.

Is it something you would be willing to contribute on?

**Comment by mta452** [comment]
@tlsa I have implemented safe allocation mechanism in develop branch. Can you test your use case against it and share feedback?

**Comment by tlsa** [comment]
@mta452 This looks good to me, thanks!

**Comment by mta452** [comment]
Fixed in `v2.5`
